name: update online notes

on:
  push:
    branches: 
      - main

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with: 
          repository: miermontoto/miermontoto
          token: ${{ secrets.PRIVATE }}

      - name: pull & update
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote
      - name: commit
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions [bot]"
          git add --all
          git commit -m "Update submodules" || echo "No changes to commit"
          git push
          
